name: Read Test Report
description: Reads the CTRF report from a specified path or a default path and sets its content as output
inputs:
  path:
    description: 'Optional path to the CTRF report file'
    required: false
    default: 'ctrf/ctrf-report.json'
outputs:
  content:
    description: The contents of the CTRF report
    value: ${{ steps.read-report.outputs.content }}
runs:
  using: 'composite'
  steps:
    - name: Read CTRF report file
      id: read-report
      shell: bash
      run: |
        REPORT_PATH="${{ inputs.path }}"
        echo "content<<EOF" >> $GITHUB_OUTPUT
        cat "$REPORT_PATH" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
